package com.cryptocoin.beans;
// Generated Apr 29, 2018 4:01:54 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FavoritesCoins generated by hbm2java
 */
@Entity
@Table(name = "Favorites_Coins", catalog = "cryptocoin")
public class FavoritesCoins implements java.io.Serializable {

	private FavoritesCoinsId id;
	private Users users;

	public FavoritesCoins() {
	}

	public FavoritesCoins(FavoritesCoinsId id, Users users) {
		this.id = id;
		this.users = users;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "coinId", column = @Column(name = "Coin_id", nullable = false, length = 50)),
			@AttributeOverride(name = "userId", column = @Column(name = "User_Id", nullable = false)) })
	public FavoritesCoinsId getId() {
		return this.id;
	}

	public void setId(FavoritesCoinsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_Id", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
