package com.cryptocoin.beans;
// Generated Apr 29, 2018 4:01:54 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FavoritesCoinsId generated by hbm2java
 */
@Embeddable
public class FavoritesCoinsId implements java.io.Serializable {

	private String coinId;
	private int userId;

	public FavoritesCoinsId() {
	}

	public FavoritesCoinsId(String coinId, int userId) {
		this.coinId = coinId;
		this.userId = userId;
	}

	@Column(name = "Coin_id", nullable = false, length = 50)
	public String getCoinId() {
		return this.coinId;
	}

	public void setCoinId(String coinId) {
		this.coinId = coinId;
	}

	@Column(name = "User_Id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritesCoinsId))
			return false;
		FavoritesCoinsId castOther = (FavoritesCoinsId) other;

		return ((this.getCoinId() == castOther.getCoinId()) || (this.getCoinId() != null
				&& castOther.getCoinId() != null && this.getCoinId().equals(castOther.getCoinId())))
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCoinId() == null ? 0 : this.getCoinId().hashCode());
		result = 37 * result + this.getUserId();
		return result;
	}

}
